### ISSUE TITLE
"File lacks basecalls!" error

### ISSUE THREAD

**Issue by hexavier** [gear-genomics/tracy#42]
Hi,
I have been trying to export ab1 basecalling into tsv, but I get the error "File lacks basecalls!". Is there anything I am missing to run it properly?
Here what I used:
tracy basecall -f tsv -o testout.tsv 10F_Kata_Arg4_Arg_F.ab1
I attach the sample file.
Thanks!
[10H_Kata_Ser1_Ser_F.zip](https://github.com/gear-genomics/tracy/files/7672161/10H_Kata_Ser1_Ser_F.zip)

**Comment by tobiasrausch** [comment]
This error message indicates that your ab1 files lack basecall positions, qualities and any primary and secondary basecalls. That usually happens when Autoanalysis is disabled on the Applied Biosystem machine. Just re-run the sequencing analysis on the machine and then tracy should work. Tracy requires the original basecall positions and cannot be run without this.
